### ISSUE TITLE
Ruckus is long gone. 

### ISSUE THREAD

**Issue by HamzaAnis** [RafayGhafoor/Ruckus-Fast-Login#1]
As far as I know, ruckus is long gone and flex is used now. What's the update? :P
P.S *Just a funny issue I got* Lol.

**Comment by RafayGhafoor** [comment]
@HamzaAnis, You might be referring to Neon?

Ruckus is the login portal which requires student sign-in to allow access to the campus wifi.

**Comment by HamzaAnis** [comment]
Is neon still in use?

**Comment by RafayGhafoor** [comment]
Nope, It's replaced by [flex](https://flexstudent.nu.edu.pk).
